### ISSUE TITLE
About Warm-Up Schedule

### ISSUE THREAD

**Issue by JialeTao** [RoyalVane/CLAN#10]
Hi, congratulations on the work! I noticed that you use a warm-up learning rate schedule where the learning rate grows up to base learning rate util 50000 iteration. Could you share any advantages about this settting?  Thanks.

**Comment by RoyalVane** [comment]
Since the two classifiers are initialized from scratch, the prediction inconsistency of them in early epoch would be extreme large and give very large weights to the adversarial loss, thus hurting the training process. A wramup for 5,000 iteration aims to relieve such issues.
