### ISSUE TITLE
how to use multi gpu

### ISSUE THREAD

**Issue by jungho-93** [RoyalVane/CLAN#16]
i have two gpu 1080ti
i want to multi gpu because 1 gpu has out of memory
so i use function" nn.dataparallel (model)" 
but my gpu don't allocate 2gpu and allocate only one gpu
(print(torch.cuda.device_count()) is 2 but don't allocate them)
do you know how to solve this problem?

**Comment by lerndeep** [comment]
did you solve the multi-GPU problem?

**Comment by RoyalVane** [comment]
This code runs only on single GPU. I think it is entirely possible to run it on multigpu but currently we may not release new version to deal with it. For your own dataset, you can adapt the dataloader to your own data structure.
