### ISSUE TITLE
The evaluation results on GTA2cityscapes

### ISSUE THREAD

**Issue by yingzicy** [RoyalVane/CLAN#19]
Hi, I trained your code on GTA52cityscapes following your instruction but failed to reproduce the evaluation results shown in your paper. The mIoU is close to the TAN baseline but worse than your method. The below is what I got. Any suggestions? Thanks!===>road:       84.44
===>sidewalk:   25.92
===>building:   78.1
===>wall:       21.57
===>fence:      24.06
===>pole:       26.74
===>light:      30.62
===>sign:       19.42
===>vegetation: 83.48
===>terrain:    31.98
===>sky:        73.76
===>person:     58.13
===>rider:      25.26
===>car:        70.47
===>truck:      35.57
===>bus:        43.26
===>train:      0.82
===>motocycle:  27.86
===>bicycle:    22.75
===> mIoU: 41.27

**Comment by ygjwd12345** [comment]
and your best model is in step 82000, do I need to test many steps in my train model?

**Comment by ygjwd12345** [comment]
@yingzicy I get a similar result 

road | 84.14
sidewalk | 15.46
building | 79.59
wall | 22.65
fence | 24.85
pole | 27.57
light | 34.08
sign | 21.95
vegetation | 83.94
terrain | 34.38
sky | 77.03
person | 58.94
rider | 27.95
car | 76.02
truck | 31.3
bus | 29.69
train | 0.17
motocycle | 28.81
bicycle | 26.47
avg/class | 41.32

**Comment by lerndeep** [comment]
I got a result higher than paper but I have a problem with multi-GPU training. could someone help me to train multi-GPU training?

**Comment by ygjwd12345** [comment]
@lerndeep can you tell me how to train the same result first? Do you have some tips?
