### ISSUE TITLE
Why so many source only in Table 1 of the paper

### ISSUE THREAD

**Issue by cnyanhao** [RoyalVane/CLAN#2]
Great work! And Congratulations for the Oral! 
Why is there so many 'source only' in Table 1 of the paper? What's the difference? Thank you.

<img width="970" alt="屏幕快照 2019-05-30 上午11 09 26" src="https://user-images.githubusercontent.com/33998324/58605736-725a4000-82cb-11e9-8db2-01a14c601b3e.png">

**Comment by RoyalVane** [comment]
Generally, the implementation of the baseline is different. For a fair comparision, we report all the source only results from their original papers.
