### ISSUE TITLE
train on multi-GPU

### ISSUE THREAD

**Issue by lerndeep** [RoyalVane/CLAN#20]
is it possible to train with multigpu?

**Comment by lerndeep** [comment]
I want to train this network with my own dataset. could you provide some idea of how can I train with my own dataset?

**Comment by RoyalVane** [comment]
Hi, lerndeep,
This code runs only on single GPU. I think it is entirely possible to run it on multigpu but currently we may not release new version to deal with it. For your own dataset, you can adapt the dataloader to your own data structure.
