### ISSUE TITLE
About the batch size

### ISSUE THREAD

**Issue by hjf1997** [RoyalVane/CLAN#23]
Hi, first congratulations on your excellent work. The only thing that I want to ask is whether the batch size is one? Did you try to use a relatively large batch size??

**Comment by RoyalVane** [comment]
Thank you for your interest in our work. The batchsize was set to 1 subject to the experimental environment.  A larger batchsize is encouraging if you adapt our code to multigpu.  But currently we may not release new version to deal with it.
