### ISSUE TITLE
How to get t-sne output ?

### ISSUE THREAD

**Issue by TFboys-lzz** [RoyalVane/CLAN#24]
Hi Yawei Luo:
    Can you explain how to get the t-sne output of Figure 3 of the paper?

**Comment by RoyalVane** [comment]
A naive solution is to upsample the feature map into the same size of the label image if you have a very large GPU memory. If not, you could try to resize the label map into 0.25x and upsample the feature map into that size, as we done in our experiments.

**Comment by TFboys-lzz** [comment]
Thanks for your reply
