### ISSUE TITLE
About data loading

### ISSUE THREAD

**Issue by BinhuiXie** [RoyalVane/CLAN#25]
Hello, thank for sharing the great work. I have a quick question. When I train the CLAN model, I find that randomly **mirror** the images and randomly **scale** the crop_size are used fo r preprocessing data, which is a little different from previous works.

When training, I can think of it as data augmentation. But, why apply the above preprocessing to the test phase? 

Thanks!

**Comment by RoyalVane** [comment]
https://github.com/RoyalVane/CLAN/blob/d66fc258f71adb09a00fcdf854d20453e8263cd2/CLAN_evaluate.py#L91

The scale and mirror were set to "False" in test phase. Where did you find this problem?

**Comment by BinhuiXie** [comment]
Thanks for your reply. 
In deed, the scale and mirror are set to ``False`` in test phase. But I still want to know how much performance improvement with the ``scale`` and ``mirror`` in training phase? 
By the way, due to the ``scale`` process, sometimes  11G memory might be not enough.

**Comment by RoyalVane** [comment]
Thank you for your question. In fact, the improvement of using "scale" and "mirror" augmentation is not significant in this UDA scenary. You could  simply set these parameters to false and evaluate the performance.
