### ISSUE TITLE
Cluster center distance

### ISSUE THREAD

**Issue by BradPitt1218** [RoyalVane/CLAN#26]
it seems that CCD part is not in your codes. would you please provide codes of calculating CCD? thank you so very much!

**Comment by RoyalVane** [comment]
Hi，BardPitt, thank you for your question. In fact, it is very easy to calculate the CCD via t-SNE map.

**Comment by lauraset** [comment]
Hi, @RoyalVane. The cluster center is the mean values of transformed features by t-sne for each class. Is that right? Below, `centers` is the cluster center. If so, the CCD  is the distance (e.g., ecludian) of the cluster center for two domains.
```python
from sklearn.manifold import TSNE
from sklearn import datasets

digits = datasets.load_digits(n_class=10)
data = digits.data		# features
label = digits.target		# labels
n_samples, n_features = data.shape # shape

ts = TSNE(n_components=2, init='pca', random_state=0)
# t-SNE
reslut = ts.fit_transform(data) # N, channels
# clustering center
classv = np.unique(label)
classn = len(classv)
centers = np.zeros((classn, 2))
for i in range(classn):
    iclass = classv[i]
    centers[i] = np.mean(reslut[label==iclass, :], axis=0)
print(centers)
```
