### ISSUE TITLE
Dataloader is always reported as wrong.

### ISSUE THREAD

**Issue by lolinkun** [RoyalVane/CLAN#3]
Hi!
I am trying to reproduce your experiments, however, I always broke in line.309 of CLAN_train.py file.
_, batch = next(trainloader_iter)
Every time my device reports wrong when meeting this sentence.

**Reported:**
_'RuntimeError: DataLoader worker (pid(s) 15186) exited unexpectedly'_

My environment is: Python 3.6.8, torch 1.1.0.
Could you please let me know how can I do to solve the issue since I really apparate this idea reported in this paper.

**Comment by RoyalVane** [comment]
Thanks for your interests in our work. I guess that the error is related to the dataset path. Please check it first. Another suggestion is to comment out the "try/except" in gta5_dataset.py or cityscapes_dataset.py, in order to locate the error.

**Comment by lolinkun** [comment]
@RoyalVane Thanks for your kindness!
Finally, I finished the setting of your codes, which spends me almost one day.
I am trying to enjoy your research.

**Comment by ygjwd12345** [comment]
@lolinkun My environment also is Python 3.6.8, torch 1.1.0. but there is a error RuntimeError: DataLoader worker (pid 105138) is killed by signal: Aborted. 
How you fix it?
Can you send you code for me yangguanglei.phd@gmail.com
