### ISSUE TITLE
About t-sne

### ISSUE THREAD

**Issue by jarvisWang0903** [RoyalVane/CLAN#5]
"As a result, the original well-segmented class are well preserved. We then map the high-dimensional features of (b), (c) and (d) to a 2-D space with t-SNE [28] shown in (e), (f) and (g)"
This is the description in your paper, I want to know which layer of output this  high-dimensional features refers to,thanks~

**Comment by RoyalVane** [comment]
The features are from the last latent layer, i.e., from layer4 in the source code.

**Comment by jarvisWang0903** [comment]
> The features are from the last latent layer, i.e., from layer4 in the source code.

thanks~  Could you share the tnse code with me?

**Comment by RoyalVane** [comment]
T-SNE is easy to implement with the package <sklearn.manifold>. You can refer to these codes below.

https://github.com/RoyalVane/SEGCN/blob/f414a92b5f8f15bf88cb94728647e099166563ac/segcn/train.py#L182

**Comment by jarvisWang0903** [comment]
> T-SNE is easy to implement with the package <sklearn.manifold>. You can refer to these codes below.
> https://github.com/RoyalVane/SEGCN/blob/f414a92b5f8f15bf88cb94728647e099166563ac/segcn/train.py#L182

get it √ thanks for your detailed reply~

**Comment by ALEX13679173326** [comment]
Excuse me.I still don't know how to use t-SNE.
The feature map we obtained is a 512-dimension tensor.How to process the tensor to use t_SNE?
Btw, how do you just visualize four categories?
