### ISSUE TITLE
About source only and t-nse

### ISSUE THREAD

**Issue by jarvisWang0903** [RoyalVane/CLAN#6]
source only-Resnet is 36.6 in many papers, but I didn't get 36.6 in my trial. Can you share your training model with me?
Another question ,is the t-nse_fearture's shape like [h * w, 2048], and the label's shape like [h * w]?  [ps: you saide you use layer4 features as input in another issues.]
In my process, i get the layer4 features which shape is [1,2048,81,61], and then i upsample the features to [1, 2048, 1024, 512]  which match the labels shape[1024, 512], and then i reshape the features to [1024 * 512, 2048] and labels to [1024 * 512]. 
Is that right?

**Comment by RoyalVane** [comment]
The source only model I trained yields mIoU around 35. However, in order to be consistent with other literatures, I borrowed the results from their tables. As for the t-sne, on the contrary to your strategy, I shrink the ground truth label to [1,19,81,61] to match the label map. While my strategy is more efficient, I think yours is also fine.

**Comment by jarvisWang0903** [comment]
thanks a lot~ I will try your strategy later~ Could you share your source only model with me? I wanna analyze the source only result image however the model I trained can not yield a mIoU as yours~ I will appreciate it if you share with me!

**Comment by RoyalVane** [comment]
I might have to retrain it since the source only experiment was done long long ago.,,

**Comment by jarvisWang0903** [comment]
Thank you very much if you have time to retrain the model~ Could you give me your contact information like wechat ~~ We can discuss more details about DA~My email is jarviswang@stu.xjtu.edu.cn

**Comment by RoyalVane** [comment]
Please refer to our oral presentation video. We have put the QR code of WeChat in it.
