### ISSUE TITLE
About the damping policy

### ISSUE THREAD

**Issue by LHXXHB** [RoyalVane/CLAN#8]
Thanks for your codes! I have doubt about the damping policy you used to replace the early stopping. I also think training 150k as AdaptSeg did is too time-consuming and shortening the total iteration steps is necessary. 
The damping weight of adversarial loss in GRL is ascending from 0 to 1 with the iteration increasing. While you set the actually opposite policy where the weight descending from 1 to 0 along with the iterating. So could you share some insights to use such a damping policy?
Thanks!

**Comment by RoyalVane** [comment]
I decreased the weight for adversarial loss dues to the observation that the segmentation loss converges to a small value in later epochs while the adversarial loss tends to dominate the training. Such strategy is only motivated by such observation. You may also try other damping policy to get a better result.

**Comment by LHXXHB** [comment]
Understood and thanks for your reply!
